---
- name: Add ec2
  hosts: localhost
  tasks:
  - amazon.aws.ec2:
    key_name: laptop
    instance_type: t2.micro
    image: ami-02f5781cba46a5e8a
    wait: yes
    count: 3
    region: us-east-2
    