--- # Connection
- name: Install Wordpress
  hosts: all
  become: true
  become_method: sudo 
  user: ec2-user
  
  tasks: 
  - name: Install prerequisites
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    package: 
      name: "{{ item }}" 
      state: present
    with_items:
    - apache2
    - php
    - php-mysql
    - wget
    - mysql-server
    - python3-pymysql
    - libapache2-mod-php
    notify: 
    - Start web server


  - name: Install mariadb
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    package: 
      name: "{{ item }}" 
      state: present
    with_items:
    - mariadb
    notify: 
    - Start DB server




  - name: Get wordpress 
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    get_url:
      url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
      dest: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      mode: '0440'

  - name: Extract wordpress
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    ansible.builtin.unarchive:
      src: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      dest: /var/www/html
      remote_src: true

  - name: Host Wordpress
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    shell: "cp -r /var/www/html/wordpress/* /var/www/html/"
    ignore_errors: true


  handlers:
  - name: Start web server
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    systemd: 
      name: apache2 
      state: restarted
      enabled: true

  - name: Start DB server
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    systemd: 
      name: mariadb 
      state: restarted
      enabled: true