---
- name: install php
  hosts: all
  become: true
  become_method: sudo
  vars: 
    wordpress_version: "4.0.32"
  tasks:
  - name: Get wordpress 
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    get_url:
      url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
      dest: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      mode: '0440'

  - name: Extract wordpress
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    ansible.builtin.unarchive:
      src: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      dest: /var/www/html
      remote_src: true

  - name: Host Wordpress
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    shell: "cp -r /var/www/html/wordpress/* /var/www/html/"
    ignore_errors: true
  