---
- name: install mysqlDB
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: install mariadb prerequisites
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    apt: pkg=software-properties-common update_cache=yes
 
  - name: install mariadb
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    apt: pkg=mariadb-server update_cache=yes
    notify: 
    - Start DB server
    
  handlers:
  - name: Start DB server
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    systemd: 
      name: mariadb 
      state: restarted
      enabled: true